packages:
  - "apps/*"
  - "packages/*"
allowBuilds:
  '@nestjs/core': false
  '@swc/core': true
  cpu-features: false
  esbuild: true
  necord: false
  protobufjs: false
  ssh2: false
minimumReleaseAgeExclude:
  - esbuild@0.25.12
  - flatted@3.4.2
  - picomatch@2.3.2
  - undici@6.27.0
overrides:
  esbuild@<=0.24.2: ^0.25.0
  flatted@<3.4.2: ^3.4.2
  picomatch@<2.3.2: ^2.3.2
  undici@<6.27.0: ^6.27.0
