/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForbiddenRouteImport } from './routes/forbidden'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as AuthedIndexRouteImport } from './routes/_authed/index'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as AuthedObservationsRouteImport } from './routes/_authed/observations'
import { Route as AuthedDeliveriesRouteImport } from './routes/_authed/deliveries'
import { Route as AuthedChannelsIndexRouteImport } from './routes/_authed/channels/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AuthedChannelsChannelIdRouteImport } from './routes/_authed/channels/$channelId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForbiddenRoute = ForbiddenRouteImport.update({
  id: '/forbidden',
  path: '/forbidden',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedIndexRoute = AuthedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedRoute,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedObservationsRoute = AuthedObservationsRouteImport.update({
  id: '/observations',
  path: '/observations',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedDeliveriesRoute = AuthedDeliveriesRouteImport.update({
  id: '/deliveries',
  path: '/deliveries',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedChannelsIndexRoute = AuthedChannelsIndexRouteImport.update({
  id: '/channels/',
  path: '/channels/',
  getParentRoute: () => AuthedRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedChannelsChannelIdRoute = AuthedChannelsChannelIdRouteImport.update({
  id: '/channels/$channelId',
  path: '/channels/$channelId',
  getParentRoute: () => AuthedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthedIndexRoute
  '/forbidden': typeof ForbiddenRoute
  '/login': typeof LoginRoute
  '/deliveries': typeof AuthedDeliveriesRoute
  '/observations': typeof AuthedObservationsRoute
  '/api/health': typeof ApiHealthRoute
  '/channels/$channelId': typeof AuthedChannelsChannelIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/channels/': typeof AuthedChannelsIndexRoute
}
export interface FileRoutesByTo {
  '/forbidden': typeof ForbiddenRoute
  '/login': typeof LoginRoute
  '/deliveries': typeof AuthedDeliveriesRoute
  '/observations': typeof AuthedObservationsRoute
  '/api/health': typeof ApiHealthRoute
  '/': typeof AuthedIndexRoute
  '/channels/$channelId': typeof AuthedChannelsChannelIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/channels': typeof AuthedChannelsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authed': typeof AuthedRouteWithChildren
  '/forbidden': typeof ForbiddenRoute
  '/login': typeof LoginRoute
  '/_authed/deliveries': typeof AuthedDeliveriesRoute
  '/_authed/observations': typeof AuthedObservationsRoute
  '/api/health': typeof ApiHealthRoute
  '/_authed/': typeof AuthedIndexRoute
  '/_authed/channels/$channelId': typeof AuthedChannelsChannelIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_authed/channels/': typeof AuthedChannelsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forbidden'
    | '/login'
    | '/deliveries'
    | '/observations'
    | '/api/health'
    | '/channels/$channelId'
    | '/api/auth/$'
    | '/channels/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/forbidden'
    | '/login'
    | '/deliveries'
    | '/observations'
    | '/api/health'
    | '/'
    | '/channels/$channelId'
    | '/api/auth/$'
    | '/channels'
  id:
    | '__root__'
    | '/_authed'
    | '/forbidden'
    | '/login'
    | '/_authed/deliveries'
    | '/_authed/observations'
    | '/api/health'
    | '/_authed/'
    | '/_authed/channels/$channelId'
    | '/api/auth/$'
    | '/_authed/channels/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthedRoute: typeof AuthedRouteWithChildren
  ForbiddenRoute: typeof ForbiddenRoute
  LoginRoute: typeof LoginRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forbidden': {
      id: '/forbidden'
      path: '/forbidden'
      fullPath: '/forbidden'
      preLoaderRoute: typeof ForbiddenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/': {
      id: '/_authed/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthedIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/observations': {
      id: '/_authed/observations'
      path: '/observations'
      fullPath: '/observations'
      preLoaderRoute: typeof AuthedObservationsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/deliveries': {
      id: '/_authed/deliveries'
      path: '/deliveries'
      fullPath: '/deliveries'
      preLoaderRoute: typeof AuthedDeliveriesRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/channels/': {
      id: '/_authed/channels/'
      path: '/channels'
      fullPath: '/channels/'
      preLoaderRoute: typeof AuthedChannelsIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/channels/$channelId': {
      id: '/_authed/channels/$channelId'
      path: '/channels/$channelId'
      fullPath: '/channels/$channelId'
      preLoaderRoute: typeof AuthedChannelsChannelIdRouteImport
      parentRoute: typeof AuthedRoute
    }
  }
}

interface AuthedRouteChildren {
  AuthedDeliveriesRoute: typeof AuthedDeliveriesRoute
  AuthedObservationsRoute: typeof AuthedObservationsRoute
  AuthedIndexRoute: typeof AuthedIndexRoute
  AuthedChannelsChannelIdRoute: typeof AuthedChannelsChannelIdRoute
  AuthedChannelsIndexRoute: typeof AuthedChannelsIndexRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedDeliveriesRoute: AuthedDeliveriesRoute,
  AuthedObservationsRoute: AuthedObservationsRoute,
  AuthedIndexRoute: AuthedIndexRoute,
  AuthedChannelsChannelIdRoute: AuthedChannelsChannelIdRoute,
  AuthedChannelsIndexRoute: AuthedChannelsIndexRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthedRoute: AuthedRouteWithChildren,
  ForbiddenRoute: ForbiddenRoute,
  LoginRoute: LoginRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
